language: java
jdk:
- openjdk8

sudo: required
dist: trusty
group: edge

before_install:
  - chmod +x gradlew
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
  - export GRADLE_OPTS=-Xmx1024m

after_success:
  - bash <(curl -s https://codecov.io/bash)

# prevent travis running gradle assemble; let the build script do it anyway
install: true

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
  - ./gradlew build --stacktrace

 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle